# syntax=docker/dockerfile:1
FROM golang:1.20.2
ENV GOPROXY=https://goproxy.cn,direct
RUN mkdir -p "$GOPATH/src"
WORKDIR /go/src
COPY . .
RUN go mod tidy
RUN go test
RUN go test -bench=Benchmark
RUN go install
EXPOSE 8080
CMD ["gower", "run"]

