version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-development
    container_name: dev
    ports:
      - "8080:8080"
    volumes:
      - ./storage/app/uploads:/go/src/storage/app/uploads
      - ./storage/logs:/go/src/storage/logs
    networks:
      - default
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: test
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./storage/app/uploads:/go/src/storage/app/uploads
      - ./storage/logs:/go/src/storage/logs
    networks:
      - default
    depends_on:
      - tidb
  prod:
    build:
      context: .
      dockerfile: Dockerfile-production
    container_name: prod
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./storage/app/uploads:/go/src/storage/app/uploads
      - ./storage/logs:/go/src/storage/logs
    networks:
      - default
    depends_on:
      - mysql
  tidb:
    build: ./third_apps/tidb
    container_name: tidb
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./third_apps/tidb/data:/var/lib/tidb
      - ./third_apps/tidb/logs:/var/log/tidb
    networks:
      - default
  mysql:
    build: ./third_apps/mysql5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "grafana"
      MYSQL_DATABASE_CHAR: "utf8mb4,utf8mb4_unicode_ci"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./third_apps/mysql5.7/data:/var/lib/mysql
    networks:
      - default
  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./third_apps/grafana/share/conf:/usr/share/grafana/conf
    networks:
      - default
    depends_on:
      - mysql
      - loki
  loki:
    image: grafana/loki:main-0295fd4
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./third_apps/loki/etc:/etc/loki
    networks:
      - default
  promtail:
    image: grafana/promtail:main-0295fd4
    container_name: promtail
    restart: always
    volumes:
      - ./third_apps/promtail/etc:/etc/promtail
      - ./storage/logs:/var/log/gower
    networks:
      - default
    depends_on:
      - loki
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.1

