# syntax=docker/dockerfile:1
FROM golang:1.20.2
ENV GOPROXY=https://goproxy.cn,direct
ENV TZ=Asia/Shanghai
RUN mkdir -p "$GOPATH/src"
WORKDIR /go/src
COPY . .
RUN ln -s storage/app/uploads public/uploads
RUN go mod tidy
RUN go install
EXPOSE 8080
RUN chmod +x dev-entrypoint.sh
ENTRYPOINT ["./dev-entrypoint.sh"]
CMD ["gower"]
