version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-development
    container_name: dev
    ports:
      - "8080:8080"
    volumes:
      - ./envs:/go/src/envs
      - ./storage:/go/src/storage
    networks:
      - default
    depends_on:
      - caddy
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: test
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./envs:/go/src/envs
      - ./storage:/go/src/storage
    networks:
      - default
    depends_on:
      - caddy
      - tidb
      - grafana
  prod:
    build:
      context: .
      dockerfile: Dockerfile-production
    container_name: prod
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./envs:/go/src/envs
      - ./storage:/go/src/storage
    networks:
      - default
    depends_on:
      - caddy
      - mysql
      - grafana
  tidb:
    build: ./third_apps/tidb
    container_name: tidb
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./third_apps/tidb/data:/var/lib/tidb
      - ./third_apps/tidb/logs:/var/log/tidb
    networks:
      - default
  mysql:
    build: ./third_apps/mysql5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./third_apps/mysql5.7/data:/var/lib/mysql
    networks:
      - default
  grafana:
    build: ./third_apps/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./third_apps/grafana/share/conf:/usr/share/grafana/conf
    networks:
      - default
    depends_on:
      - promtail
      - loki
  loki:
    build: ./third_apps/loki
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./third_apps/loki/etc:/etc/loki
    networks:
      - default
  promtail:
    build: ./third_apps/promtail
    container_name: promtail
    restart: always
    volumes:
      - ./third_apps/promtail/etc:/etc/promtail
      - ./storage/logs:/var/log/gower
    networks:
      - default
    depends_on:
      - loki
  caddy:
    build: ./third_apps/caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./third_apps/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./third_apps/caddy/site:/srv
      - ./third_apps/caddy/data:/data
      - ./third_apps/caddy/config:/config
      - ./public/static:/public/static
      - ./storage/app/upload:/public/upload
    networks:
      - default
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.1

