# syntax=docker/dockerfile:1
FROM golang:1.20.2
ENV GOPROXY=https://goproxy.cn,direct
ENV TZ=Asia/Shanghai
RUN mkdir -p "/go/src"
WORKDIR /go/src
COPY . .
RUN go mod tidy
RUN go install
EXPOSE 8080
RUN chmod +x entrypoint-dev-full.sh
ENTRYPOINT ["./entrypoint-dev-full.sh"]
CMD ["gower"]
