# syntax=docker/dockerfile:1
FROM golang:1.23.2
ENV GOPROXY=https://goproxy.cn,direct
ENV TZ=Asia/Shanghai
RUN mkdir -p "/go/src"
WORKDIR /go/src
COPY .. .
RUN go mod tidy
RUN go install
EXPOSE 8080
RUN chmod +x docker/entrypoint-dev-full.sh
ENTRYPOINT ["./docker/entrypoint-dev-full.sh"]
CMD ["gower"]
