version: '1.0'
name: test
displayName: test
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-68e9eaaf
    displayName: go test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.12'
        commands:
          - '# 安装 nvm (Node 版本管理器)'
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          - ''
          - '# 下载并安装 Node.js（可能需要重启终端）'
          - nvm install 18
          - ''
          - '# 测试 node 安装'
          - node -v
          - ''
          - '# 安装 pnpm'
          - corepack enable pnpm
          - ''
          - '# 安装 node_module'
          - pnpm install
          - ''
          - '# 打前端包'
          - npm run dev
          - ''
          - '# 默认使用goproxy.cn用户可手动调整'
          - export GOPROXY=https://goproxy.cn
          - ''
          - '# 同步整理'
          - go mod tidy
          - ''
          - '# 默认的单元测试命令'
          - go test -tags tmpl,static
          - ''
          - '# 构建'
          - go build -o gower -tags tmpl,static
          - ''
          - '# 输出版本号'
          - gower --version
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
