name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker image
        run: docker build . --file ./docker/Dockerfile-development-full --tag gower:$(date +%s)
