name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List files in repository
        run: ls -l

      - name: Chmod +x
        run: sudo chmod +x docker/run-dev-full.sh

      - name: Run dev full
        run: docker/run-dev-full.sh
